# core/config.py

# --- CAPABILITY TIERS (The New Standard) ---
CAPABILITY_GENERAL = "GENERAL"       # Formerly 'student'
CAPABILITY_ELEVATED = "ELEVATED"     # Formerly 'researcher'
CAPABILITY_INTERNAL = "INTERNAL"     # Formerly 'admin'

# --- SECURITY THRESHOLDS ---
SEMANTIC_THRESHOLD_HIGH = 0.48
SEMANTIC_THRESHOLD_MEDIUM = 0.22
EDUCATIONAL_THRESHOLD = 0.45
DOMAIN_THRESHOLD = 0.22
CACHE_SIMILARITY_THRESHOLD = 0.95
META_INTENT_THRESHOLD = 0.40

 